in_channels : 3
num_classes : 50
lr : 0.01
weight_decay : 0.0001
epochs : 300
batch_size : 128
backbone : 'inception'
optimizer : 'sgd'
momentum : 0.9
scheduler : 'cos'
augment: cutmix
ssl_prob: 0.5
num_classes_sub: 10
resume: 'ckpt/WebVision/ssl.pth.tar'
ssl_pretrained: True
permute_strategy: confident
warmup: 0
threshold: 0.5
reduce_alg: pca
beta: 0.5